name: parkinsons-voice
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - librosa=0.10.1
  - transformers=4.34.0
  - datasets=2.14.5
  - scipy=1.11.2
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pytest=7.4.2
  - black=23.7.0
  - flake8=6.0.0
  - mypy=1.5.1
  - pip
  - pip:
    - wandb==0.21.3