# Data Configuration

# Dataset paths
paths:
  data_dir: "data"
  hc_dir: "data/HC_AH"
  pd_dir: "data/PD_AH"
  demographics_file: "data/Demographics_age_sex.xlsx"
  dataset_csv: "data/dataset_metadata.csv"

# Data preprocessing
preprocessing:
  target_sample_rate: 16000
  max_duration: 10.0
  normalize_audio: true
  processor_name: "facebook/wav2vec2-base-960h"

# Dataset split configuration
splits:
  train_val_split: 0.2
  stratify: true
  random_state: 42

# Data loading
dataloader:
  num_workers: 4
  pin_memory: true
  shuffle: true
  drop_last: true